<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TairinemMobile_SysEMM</name>
   <tag></tag>
   <elementGuidId>1fb41df4-c20b-49bb-b241-3569d2097a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-pjax-container']/div/div[3]/div/ul/li[4]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-align-middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click</name>
      <type>Main</type>
      <value>{&quot;event_type&quot;:&quot;search_result.click&quot;,&quot;payload&quot;:{&quot;page_number&quot;:1,&quot;per_page&quot;:10,&quot;query&quot;:&quot;sysemm&quot;,&quot;result_position&quot;:4,&quot;click_id&quot;:195088382,&quot;result&quot;:{&quot;id&quot;:195088382,&quot;global_relay_id&quot;:&quot;MDEwOlJlcG9zaXRvcnkxOTUwODgzODI=&quot;,&quot;model_name&quot;:&quot;Repository&quot;,&quot;url&quot;:&quot;https://github.com/Tairinem/Mobile_SysEMM&quot;},&quot;originating_url&quot;:&quot;https://github.com/search?q=sysemm&quot;,&quot;user_id&quot;:null}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click-hmac</name>
      <type>Main</type>
      <value>9b9cca5f043210fcd3a77c1affa8e400c647be85e39419d411422dd7763a5c3d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Tairinem/Mobile_SysEMM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tairinem/Mobile_SysEMM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-pjax-container&quot;)/div[@class=&quot;container-lg px-md-2 mt-lg-4 clearfix&quot;]/div[@class=&quot;col-12 col-md-9 float-left px-2 pt-3 pt-md-0 codesearch-results&quot;]/div[@class=&quot;px-2&quot;]/ul[@class=&quot;repo-list&quot;]/li[@class=&quot;repo-list-item hx_hit-repo d-flex flex-justify-start py-4 public source&quot;]/div[@class=&quot;mt-n1&quot;]/div[@class=&quot;f4 text-normal&quot;]/a[@class=&quot;v-align-middle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-pjax-container']/div/div[3]/div/ul/li[4]/div[2]/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on Dec 10, 2019'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objective-C'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tairinem/Mobile_']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Tairinem/Mobile_SysEMM')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
